language: rust

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo bench --verbose

rust:
  - stable
  - beta
  - nightly

os:
  - windows
  - linux

arch:
  - amd64
  - arm64

matrix:
  allow_failures:
    - rust: nightly